### ISSUE TITLE
SCK

### ISSUE THREAD

**Issue by wisnusatriyo** [M-A-P-E/RollJam-315MHz-433MHz#2]
Hi
In your code I could not find SCK connection. Do we ignore this pin? and can we can the Teensy 3.2 to Arduino Uno or Nano? Thanks for Indonesia

int cs_rx = 10;
int cs_jam = 20;
int gdo0_rx = 2;
int gdo0_jam = 3;

int mosi = 11;
int miso = 12;

int pushButton = 4;

**Comment by Petros626** [comment]
Hello,

I saw it in the description, if you want to convert the Code from the Teensy 3.1 to a Arduino Nano oder something like that, you must change a few things. I don't know, what else like GPIO Pins declarations must be changed, but it will cost you some research
