### ISSUE TITLE
Adjust Freq

### ISSUE THREAD

**Issue by wisnusatriyo** [M-A-P-E/RollJam-315MHz-433MHz#3]
Hi There.
In your code the carrier freq 433.795 (0x10,0xAF,0xC1) as shown below. How do I change to specific Freq to 433.925. Is there any reference or calculator to convert it?

// Carrier frequency = 433.795 MHz
//#define CC1101_DEFVAL_FREQ2_433  0x10        // Frequency Control Word, High Byte
//#define CC1101_DEFVAL_FREQ1_433  0xAF        // Frequency Control Word, Middle Byte
//#define CC1101_DEFVAL_FREQ0_433  0xC1      // Frequency Control Word, Low Byte  

Wisnu - Indonesia

**Comment by Petros626** [comment]
Hello,

the frequency should be changed with the different registers the author find out, but for my knowledge it's only 315 and 433 MHz for keyless go systems. It depends of your country. Check the data sheet of your µC this would be my approach.
